<MyLayout>
    BoxLayout:
        orientation:'vertical'
        size:root.width,root.height


        Label:
            id:click_label
            text:'Pick Favorite Pizza Below'   
            font_size:32

        Spinner:
            id:spinner_id
            text:"Favorite Pizza"
            values:["Papperoni","Cheese","Mushroom"]     

            on_text:root.spinnerCLicked(spinner_id.text)

        Label:
            text:""    